### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Vanleya** [VinAIResearch/HyperInverter#13]
Traceback (most recent call last):
  File "scripts/inference.py", line 100, in <module>
    run()
  File "scripts/inference.py", line 39, in run
    net = HyperInverter(opts)
  File "./models/hyper_inverter.py", line 58, in __init__
    self.load_weights()
  File "./models/hyper_inverter.py", line 102, in load_weights
    G_original = ckpt["G_ema"]
TypeError: tuple indices must be integers or slices, not str

I don't understand why I have this problem?

**Comment by Vanleya** [comment]
solved，use official stylegan2 model
